In [1]:
import numpy as np
arr=([1,2,3,6,4,5])
print("Reverse array:", arr[::-1])

Reverse array: [5, 4, 6, 3, 2, 1]


In [2]:
arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flatten:", arr1.flatten())

Flatten: [1 2 3 2 4 5 1 2 3]


In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("comparing: ", np.array_equal(arr1, arr2))


comparing:  True


In [4]:
x = np.array([1, 2, 3, 4, 5, 2, 1, 2, 1, 1])
y = np.array([1, 1, 1, 2, 3, 2, 4, 4, 3, 3, 1])
print("Most frequent in x:", np.bincount(x).argmax())
print( np.where(x == np.bincount(x).argmax()))
print("Most frequent in y:", np.bincount(y).argmax())
print( np.where(y == np.bincount(y).argmax()))


Most frequent in x: 1
(array([0, 6, 8, 9]),)
Most frequent in y: 1
(array([ 0,  1,  2, 10]),)


In [6]:
gfg = np.matrix([[4, 1,9], [12, 3, 1], [4, 5, 6]])
print("Sum of all elements:", gfg.sum())
print("Sum rowwise:", gfg.sum(axis=1))
print("Sum column-wise:", gfg.sum(axis=0))

Sum of all elements: 45
Sum row-wise: [[14]
 [16]
 [15]]
Sum column-wise: [[20  9 16]]


In [7]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Sum of diagonal:", np.trace(n_array))
print("Eigenvalues:", np.linalg.eig(n_array))
print("Inverse:", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))




Sum of diagonal: 176
Eigenvalues: EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [8]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("Matrix product: ", np.dot(p, q))
print("Covariance: ", np.cov(p, q))


Matrix product:  [[16 19]
 [26 31]]
Covariance:  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [6]:
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:", np.inner(x, y))
print("Outer product:", np.outer(x, y))
print("Cartesian product: ", np.array(np.meshgrid(x, y)).T.reshape(-1, 2))

Inner product: [[17 52]
 [13 62]]
Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:  [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [11]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute values:\n", np.abs(array))
print("ROWS:" )
print("25th percentile:", np.percentile(array, 25, axis=1))
print("50th percentile:", np.percentile(array, 50, axis=1))
print("75th percentile:", np.percentile(array, 75, axis=1))
print("Mean :", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Std deviation :", np.std(array, axis=1))
print("Across Coloumns: ")
print("25th percentile:", np.percentile(array, 25, axis=0))
print("50th percentile:", np.percentile(array, 50, axis=0))
print("75th percentile:", np.percentile(array, 75, axis=0))
print("Mean (columns):", np.mean(array, axis=0))
print("Median (columns):", np.median(array, axis=0))
print("Std deviation (columns):", np.std(array, axis=0))


Absolute values:
 [[1 2 3]
 [4 5 6]]
ROWS:
25th percentile: [-0.5 -5. ]
50th percentile: [ 1. -4.]
75th percentile: [2.  0.5]
Mean : [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Std deviation : [2.05480467 4.78423336]
Across Coloumns: 
25th percentile: [-2.75 -0.25 -3.75]
50th percentile: [-1.5  1.5 -1.5]
75th percentile: [-0.25  3.25  0.75]
Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Std deviation (columns): [2.5 3.5 4.5]


In [12]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Truncate:", np.trunc(a))
print("Round: ",np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncate: [-1. -1. -0.  0.  1.  1.  3.]
Round:  [-2. -2. -0.  0.  2.  2.  3.]


In [13]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array))
print("Indices sorted:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:])

Sorted array: [ 10  16  16  52  54  62 453]
Indices sorted: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]


In [14]:
array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer = array2[np.floor(array2) == array2]
floats = array2[np.floor(array2) != array2]
print("Integers only:", integer)
print("Floats only:", floats)


Integers only: [1. 2. 3. 2.]
Floats only: [1.2 2.2]
